services:
  - type: web
    name: backend
    env: python
    rootDir: .
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///./fastapi-practice.db"
    plan: free