# render.yaml
services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///backend/fastapi-practice.db"
    plan: free